In [5]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df= pd.read_csv('C:\\Users\\Hp\\OneDrive\\Documents\\ola_cab_services.csv')
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating
0,28-01-2024,06:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,...,NaN,0,NaN,0,NaN,868.06,Wallet,28.50,4.4,4.4
1,26-01-2024,03:00:00,CNR2871422,Cancelled by Driver,201414,Mini,Area-7,Area-6,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
2,15-01-2024,16:00:00,CNR6875935,Cancelled by Driver,301629,Bike,Area-40,Area-24,NaN,NaN,...,NaN,1,Personal & Car related issues,0,NaN,NaN,NaN,NaN,NaN,NaN
3,02-01-2024,22:00:00,CNR6798834,Cancelled by Driver,319684,Prime Sedan,Area-11,Area-24,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
4,30-01-2024,22:00:00,CNR9661713,Incomplete,330283,Bike,Area-41,Area-45,NaN,NaN,...,NaN,0,NaN,1,Other Issue,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,02-01-2024,00:00:00,CNR7299340,Success,454202,eBike,Area-39,Area-34,11.53,2.42,...,NaN,0,NaN,0,NaN,1217.43,Card,10.52,4.1,3.2
49995,27-01-2024,02:00:00,CNR0378586,Success,349873,Auto,Area-17,Area-21,5.56,9.05,...,NaN,0,NaN,0,NaN,1369.51,UPI,11.04,5.0,4.3
49996,17-01-2024,23:00:00,CNR2461856,Cancelled by Driver,880053,Auto,Area-37,Area-43,NaN,NaN,...,NaN,1,More than permitted people in there,0,NaN,NaN,NaN,NaN,NaN,NaN
49997,18-01-2024,22:00:00,CNR9524579,Success,752806,eBike,Area-48,Area-29,5.15,13.72,...,NaN,0,NaN,0,NaN,1930.49,UPI,14.49,3.1,4.5
49998,28-01-2024,14:00:00,CNR3698787,Success,159552,Bike,Area-1,Area-37,14.89,28.07,...,NaN,0,NaN,0,NaN,1534.66,Cash,4.60,3.3,4.1

In [4]:
cat_data=df[['Booking Status','Vehicle Type','Reason for Cancelling by Driver','Reason for Cancelling by Customer','Payment Method']]
cat_data

,Booking Status,Vehicle Type,Reason for Cancelling by Driver,Reason for Cancelling by Customer,Payment Method
0,Success,Auto,NaN,NaN,Wallet
1,Cancelled by Driver,Mini,The customer was coughing/sick,NaN,NaN
2,Cancelled by Driver,Bike,Personal & Car related issues,NaN,NaN
3,Cancelled by Driver,Prime Sedan,The customer was coughing/sick,NaN,NaN
4,Incomplete,Bike,NaN,NaN,NaN
...,...,...,...,...,...
49994,Success,eBike,NaN,NaN,Card
49995,Success,Auto,NaN,NaN,UPI
49996,Cancelled by Driver,Auto,More than permitted people in there,NaN,NaN
49997,Success,eBike,NaN,NaN,UPI
49998,Success,Bike,NaN,NaN,Cash

In [134]:
#B1] Which date had the highest average booking value?
df.groupby("Date")["Booking Value"].mean().idxmax()

'28-01-2024'

In [147]:
#B2] Which drop location has the highest average driver rating?
df.groupby("Drop Location")["Driver Ratings"].mean().idxmax()

'Area-15'

In [144]:
#B3] Which pickup location has the lowest customer ratings?
df.groupby("Pickup Location")["Customer Rating"].mean().tail(1)

Pickup Location
Area-9    3.986402
Name: Customer Rating, dtype: float64

In [26]:
#B4] What was the average ride distance for the first five dates in the dataset?
df.groupby("Date")["Ride Distance"].mean().head()

Date
01-01-2024    25.854491
02-01-2024    25.510652
03-01-2024    25.112378
04-01-2024    25.636259
05-01-2024    25.319328
Name: Ride Distance, dtype: float64

In [135]:
#B5] Which date recorded the highest number of cash payments?
df[df["Payment Method"] == "Cash"].groupby("Date")["Booking ID"].count().idxmax()

'09-01-2024'

In [149]:
#B6] Which customer ID spent the highest total booking value?
df.groupby("Customer ID")["Booking Value"].sum().sort_values(ascending=False).head(1)

Customer ID
580524    5078.2
Name: Booking Value, dtype: float64

In [151]:
#B7] What is the average ride distance for each booking status?
df.groupby("Booking Status")["Ride Distance"].mean()

Booking Status
Cancelled by Customer          NaN
Cancelled by Driver            NaN
Incomplete                     NaN
Success                  25.447143
Name: Ride Distance, dtype: float64

In [38]:
#B8] Which booking status gets the highest average driver rating?
df.groupby("Booking Status")["Driver Ratings"].mean().idxmax()

'Success'

In [45]:
#B9] Which booking status is most common for bike rides?
df[df["Vehicle Type"].str.lower() == "bike"]["Booking Status"].mode()[0]

'Success'

In [50]:
#B10] What is the average booking value for each payment method
df.groupby("Payment Method")["Booking Value"].mean()

Payment Method
Card      1011.791802
Cash      1025.278593
UPI       1021.863211
Wallet    1034.603940
Name: Booking Value, dtype: float64

In [56]:
#B11] What is the average ride distance for each payment method?
df.groupby("Payment Method")["Ride Distance"].mean()

Payment Method
Card      25.287289
Cash      25.477466
UPI       25.582288
Wallet    25.438057
Name: Ride Distance, dtype: float64

In [60]:
#B12] Which payment method has the highest number of successful rides?
df[df["Booking Status"] == "Success"]["Payment Method"].value_counts()

Payment Method
Cash      8552
UPI       8428
Card      8280
Wallet    8224
Name: count, dtype: int64

In [152]:
#B13] Which payment method gets the highest driver ratings?
df.groupby("Payment Method")["Driver Ratings"].mean().idxmax()

'Wallet'

In [70]:
#B14] What is the average booking value for each vehicle type?
df.groupby("Vehicle Type")["Booking Value"].mean()

Vehicle Type
Auto           1017.254089
Bike           1021.592971
Mini           1024.167753
Prime Plus     1021.435192
Prime SUV      1024.746587
Prime Sedan    1027.016463
eBike          1027.479819
Name: Booking Value, dtype: float64

In [153]:
#B15] Which vehicle type has the highest average ride distance?
df.groupby("Vehicle Type")["Ride Distance"].mean().idxmax()

'Auto'

In [80]:
#B16] Which vehicle type is most often paid by cash?
df[df["Payment Method"] == "Cash"]["Vehicle Type"].value_counts().idxmax()

'Mini'

In [83]:
#B17] Which vehicle type has the highest number of successful rides?
df[df["Booking Status"] == "Success"]["Vehicle Type"].value_counts().idxmax()

'Bike'

In [86]:
#B18] Which vehicle type gets the lowest driver ratings?
df.groupby("Vehicle Type")["Driver Ratings"].mean().idxmin()

'Prime Plus'

In [91]:
#B19] Which pickup location has the highest average booking value? 
df.groupby("Pickup Location")["Booking Value"].mean().idxmax()

'Area-18'

In [94]:
#B20] Which pickup location has the longest average ride distance?
df.groupby("Pickup Location")["Ride Distance"].mean().idxmax()

'Area-31'

In [100]:
#B21] Which pickup location has the most cash payments?
df[df["Payment Method"] == "Cash"]["Pickup Location"].value_counts().idxmax()

'Area-39'

In [101]:
#B22] Which pickup location is most common for auto rides?
df[df["Vehicle Type"] == "Auto"]["Pickup Location"].value_counts().idxmax()

'Area-39'

In [106]:
#B23] Which drop location has the most successful rides?
df[df["Booking Status"] == "Success"]["Drop Location"].value_counts().idxmax()

'Area-8'

In [110]:
#B24] Which drop location is most common for bike rides?
df[df["Vehicle Type"]=="Bike"]["Drop Location"].value_counts().idxmax()

'Area-39'

In [111]:
#B25] Which vehicle type is most common for rides above 20 km?
df[df["Ride Distance"] > 20]["Vehicle Type"].value_counts().idxmax()

'Bike'

In [116]:
#B26] Do rides longer than 40 km get better or worse ratings?
df.groupby(df["Ride Distance"] > 40)["Driver Ratings"].mean()

Ride Distance
False    4.002645
True     4.004596
Name: Driver Ratings, dtype: float64

In [119]:
#B27] Which payment method has the highest average booking value?
df.groupby("Payment Method")["Booking Value"].mean().idxmax()

'Wallet'

In [155]:
#B28] Which pickup location has the lowest customer ratings?
df.groupby('Pickup Location')['Customer Rating'].mean().idxmax()

'Area-32'

In [156]:
#B29] Which pickup location has the lowest average booking value?
df.groupby("Pickup Location")["Booking Value"].mean().idxmin()

'Area-34'

In [133]:
#B30] Which payment method gets the best customer ratings?
df.groupby("Payment Method")["Customer Rating"].mean().idxmax()

'Card'